project:
  type: website
  output-dir: docs
  resources:
    - "profile.jpg"

website:
  title: "In My Lightcone"
  site-url: https://www.inmylightcone.com
  description: "Exploring ideas across past, present, and future lightcones"
  favicon: imlc_logo.jpg
  
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About" 
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Ramblings"
        file: ramblings.qmd
      - text: "Resources"
        file: resources.qmd
    right:
      - icon: github
        href: https://github.com/arunravishankar
      - icon: linkedin
        href: https://www.linkedin.com/in/arunravishankar
      - icon: bluesky
        href: https://bsky.app/profile/arunravishankar.bsky.social

format:
  html:
    theme:
      light: [cosmo, styles.css]
      dark: [cosmo, styles-dark.css]