project:
  type: website
  output-dir: docs

website:
  title: "In My Lightcone"
  site-url: https://www.inmylightcone.com
  description: "Exploring ideas across past, present, and future lightcones"
  
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About" 
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Ramblings"
        file: ramblings.qmd
      - text: "Resources"
        file: resources.qmd
    right:
      - icon: github
        href: https://github.com/arunravishankar
      - icon: linkedin
        href: https://www.linkedin.com/in/arunravishankar
      - icon: bluesky
        href: https://bsky.app/profile/arunravishankar.bsky.social
  comments:
    giscus:
      repo: "arunravishankar/in-my-lightcone"
      category: "Blog Comments"
      mapping: "pathname"
      reactions-enabled: true
      input-position: "bottom"
      theme: "light_protanopia"
      language: "en"
format:
  html:
    theme: cosmo
    css: styles.css